---
Name: mwm-routes
After:
  - 'framework/*'
  - 'cms/*'
---
Director:
  rules:
    'email-subscriptions//$Action/$Email/$Lists': 'SendThis_Controller'
    '$Slug/mail-footer.gif': 'SendThis_Tracker'